import {
  AlertTriangle,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Cake,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  Camera,
  ChefHat,
  ClipboardCheck,
  ClipboardList,
  Code2,
  Coffee,
  Cog,
  Coins,
  DollarSign,
  Flame,
  Focus,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Leaf,
  Lightbulb,
  ListChecks,
  Mail,
  MailCheck,
  Megaphone,
  MessageSquareHeart,
  Mic,
  Monitor,
  Music,
  Package,
  Palette,
  Plane,
  Presentation,
  QrCode,
  Quote,
  Receipt,
  Scale,
  Scroll,
  ScrollText,
  Search,
  Share2,
  Shirt,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Tag,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Trophy,
  User,
  UserCog,
  Users,
  UsersRound,
  UtensilsCrossed,
  Wallet,
  Wrench,
  Info,
  type LucideIcon,
} from "lucide-react";
import type { SitemapIconName } from "@/lib/sitemap-catalogue";

const ICON_REGISTRY: Record<SitemapIconName, LucideIcon> = {
  home: Home,
  user: User,
  users: Users,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "clipboard-check": ClipboardCheck,
  "list-checks": ListChecks,
  plane: Plane,
  wallet: Wallet,
  "bar-chart-3": BarChart3,
  "scroll-text": ScrollText,
  sparkles: Sparkles,
  cog: Cog,
  palette: Palette,
  bell: Bell,
  "message-square-heart": MessageSquareHeart,
  "user-cog": UserCog,
  monitor: Monitor,
  "qr-code": QrCode,
  search: Search,
  megaphone: Megaphone,
  cake: Cake,
  package: Package,
  scroll: Scroll,
  coffee: Coffee,
  scale: Scale,
  "help-circle": HelpCircle,
  quote: Quote,
  "utensils-crossed": UtensilsCrossed,
  gift: Gift,
  "users-round": UsersRound,
  presentation: Presentation,
  "trending-up": TrendingUp,
  briefcase: Briefcase,
  "chef-hat": ChefHat,
  "book-open": BookOpen,
  smile: Smile,
  "dollar-sign": DollarSign,
  receipt: Receipt,
  coins: Coins,
  "share-2": Share2,
  timer: Timer,
  target: Target,
  trophy: Trophy,
  music: Music,
  info: Info,
  image: ImageIcon,
  mail: Mail,
  wrench: Wrench,
  lightbulb: Lightbulb,
  mic: Mic,
  globe: Globe,
  tag: Tag,
  heart: Heart,
  "graduation-cap": GraduationCap,
  brain: Brain,
  "mail-check": MailCheck,
  thermometer: Thermometer,
  "calendar-heart": CalendarHeart,
  leaf: Leaf,
  "code-2": Code2,
  camera: Camera,
  "building-2": Building2,
  "clipboard-list": ClipboardList,
  shirt: Shirt,
  star: Star,
  focus: Focus,
  snowflake: Snowflake,
  gauge: Gauge,
  flame: Flame,
  "alert-triangle": AlertTriangle,
};

export function resolveSitemapIcon(name: SitemapIconName): LucideIcon {
  return ICON_REGISTRY[name] ?? Sparkles;
}
